name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: 安装依赖
      run: yarn install --frozen-lockfile

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: ET-yzk/ET-yzk.github.io
        TARGET_BRANCH: v2
        BUILD_SCRIPT: yarn && yarn run docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://blog.yzketx.online
