name: Build and Deploy:to other custom branch

on:
  push:
    branches:
      - master

# permissions:
#   contents: write

jobs:
  # deploy-gh-pages:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         # if need Git sub-moudle，light under line
  #         # submodules: true

  #     - name: install pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         run_install: true
  #         version: 8

  #     - name: setting Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #         cache: pnpm

  #     - name: build docs
  #       env:
  #         NODE_OPTIONS: --max_old_space_size=8192
  #       run: |-
  #         pnpm run docs:build
  #         > docs/.vuepress/dist/.nojekyll

  #     - name: deploy docs
  #       uses: JamesIves/github-pages-deploy-action@v4
  #       with:
  #         # 这是文档部署到的分支名称
  #         branch: v2
  #         folder: docs/.vuepress/dist

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: ET-yzk/ET-yzk.github.io
          TARGET_BRANCH: v2
          BUILD_SCRIPT: corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run docs:build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://blog.yzketx.online
          COMMIT_MESSAGE:  Auto deploy by the Vuepress-deploy
